// Localization dictionary for EN/ES language support

export type Lang = "en" | "es";

export const translations: Record<Lang, Record<string, string | string[]>> = {
  en: {
    "page.title": "Jairo Garcia Antolin // Software & AI Developer",
    "nav.home": "Home",
    "nav.about": "About",
    "nav.tech": "Tech",
    "nav.projects": "Projects",
    "nav.education": "Education",
    "nav.career": "Career",
    "nav.contact": "Contact",
    "hero.typewriter": ["i build modern solutions", "i design scalable systems", "i focus on clean architecture", "i prioritize performance"],
    "hero.description": 'My aim is to deliver <span class="text-gray-200">modern software solutions</span> that enhance user experiences and drive business success through efficiency and scalability.',
    "hero.cta": "Let's build together",
    "hero.cv.english": "English",
    "hero.cv.spanish": "Spanish",
    "about.whatido.title": 'What i <span class="text-gray-400">do</span>',
    "about.whatido.p1": "Software developer based in Málaga-Spain, specializing in building robust and scalable systems.",
    "about.whatido.p2": 'I\'m currently working towards expanding my technical horizon into <span class="text-gray-200">Data Engineering, Artificial Intelligence & Backend solutions.</span><br /><br />I am passionate about creating systems that not only function flawlessly but also process, validate, and leverage data intelligently.',
    "about.whoami.part1": "Who am",
    "about.whoami.part2": "i",
    "about.whoami.p1": 'I\'m just a guy who loves <span class="text-gray-200">technology, videogames and discovering things.</span>',
    "about.whoami.learning": 'I\'m addicted to the feeling of <span class="text-gray-200">learning</span> new things:',
    "about.whoami.typewriter": [" cities", " lenguages", " technologies", " videogames", " music", " movies", " cultures"],
    "about.whoami.p3": "I'm certain that's how we keep on growing and rediscovering ourselves.",
    "about.whoami.elsword": 'My favourite childhood game was Elsword, a side scrolling 2.5D action game where i <span class="text-gray-200">competed</span> against many other skilled players around the world. <span class="text-gray-200">I won the biggest European tournament of Elsword\'s history back in 2016,</span> i traveled to Cologne (Germany) where i would be crowned as the European champion at the Gamescom after a well-heated long competition.',
    "about.whoami.discipline": 'I believe that the same kind of <span class="text-gray-200">discipline</span> i have to win that trophy is also required to <span class="text-gray-200">optimize, build and come up with solutions</span> that can actually help people and improve systems.',
    "tech.title.main": "Tech",
    "tech.title.accent": "stack",
    "tech.subtitle": "Reliable tools that deliver",
    "tech.frontend.title": "Frontend",
    "tech.frontend.desc": "UX/UI design",
    "tech.backend.title": "Backend",
    "tech.backend.desc": "Architecture & databases",
    "tech.devops.title": "Dev Ops",
    "tech.devops.desc": "Deployment & collaboration",
    "tech.ai.title": "AI Tools",
    "tech.ai.desc": "Productivity & coding assistance",
    "projects.title.main": "Built",
    "projects.title.accent": "products",
    "projects.subtitle": "Keep learning, keep delivering",
    "projects.btn.live": "Live",
    "projects.btn.features": "Features",
    "projects.btn.repo": "Repo",
    "projects.modal.label": "Project Details",
    "projects.0.title": "Sampleton: Audio Library App",
    "projects.0.description": "Users can upload, browse, and stream audio samples, organize them into playlists, leave comments, and like their favorite tracks. This full-stack application features JWT authentication, dark/white mode, responsive design, and a persistent audio player.",
    "projects.0.features.0": "Persistent global audio player engine built on React Layout/Outlet state, ensuring uninterrupted playback across client-side route transitions.",
    "projects.0.features.1": "Complete RESTful CRUD management for audio tracks, custom cover art, and playlists backed by Neon PostgreSQL storage.",
    "projects.0.features.2": "JWT-based security architecture featuring protected routes, automatic token expiration handling via Axios interceptors, and 1-click recruiter demo account.",
    "projects.0.features.3": "Backend-enforced object-level permission guards in Django REST ViewSets, restricting delete/edit actions exclusively to resource owners.",
    "projects.0.features.4": "Interactive track detail interface featuring simulated waveform visualization, play count tracking, likes toggling, and track-level comment feeds.",
    "projects.0.features.5": "Client & server-side form validation using regex patterns for strict password complexity, email verification, and multipart/form-data upload constraints.",
    "projects.0.features.6": "Multi-tab personal library dashboard and real-time search engine for instant filtering across tracks, genres, playlists, and user interactions.",
    "projects.0.features.7": "Automated API testing suite implemented with Pytest (pytest-django), validating authentication endpoints, file uploads, and database operations.",
    "projects.1.title": "RPG Game System Prototype",
    "projects.1.description": "Developed from scratch to master core programming fundamentals. It features a dynamic dialogue engine, an interactive inventory UI, and a robust room persistency and save/load system using JSON serialization, all paired with original handmade pixel art.",
    "projects.1.features.0": "Persistency between rooms and save/load system using JSON parsing. To test persistency between rooms, there's a room at the end of the right path.",
    "projects.1.features.1": "Dialogue system using switch statements and custom scripts for text animations.",
    "projects.1.features.2": "Inventory system with menu UI, using arrays and custom scripts.",
    "projects.1.features.3": "Handmade 2D pixel art graphics and animations.",
    "projects.1.controls.title": "Keyboard Controls",
    "projects.1.controls.action.0": "Movement",
    "projects.1.controls.action.1": "Run",
    "projects.1.controls.action.2": "Interact",
    "projects.1.controls.action.3": "Menu",
    "projects.1.controls.action.4": "Save Game",
    "projects.1.controls.action.5": "Load Game",
    "projects.1.controls.action.6": "Exit Game",
    "projects.2.title": "Web Portfolio",
    "projects.2.description": "A high-performance, modern developer portfolio built with Astro 5 and Tailwind CSS v4. Designed with focus on clean architecture, smooth animations, optimized asset delivery, and responsive UI/UX.",
    "projects.2.features.0": "Uses Astro, Tailwind CSS and JavaScript to deliver a static site optimized for performance and SEO.",
    "projects.2.features.1": "Engineered fluid, high-performance scroll reveal animations using Intersection Observer and hardware-accelerated CSS transitions.",
    "projects.2.features.2": "Leveraged Astro's Static Site Generation (SSG) to deliver highly optimized asset loading and superior SEO performance.",
    "projects.2.features.3": "Implemented a mobile-first, responsive UI featuring touch-optimized navigation and pure Tailwind CSS interactive components.",
    "projects.3.title": "Fantasy Stats Analyzer",
    "projects.3.description": "An analytical engine designed to optimize fantasy sports rosters. It scrapes and aggregates player performance metrics and scoring systems to provide real-time market valuations.",
    "projects.3.features.0": "Automated web scraping pipeline handling 10k+ data points daily.",
    "projects.3.features.1": "Machine learning model integration for predictive scoring.",
    "education.title.main": "Academic ",
    "education.title.accent": "journey",
    "education.subtitle": "Knowledge i keep expanding",
    "education.0.year": "2026 - Present",
    "education.0.title": "Specialization Diploma in AI & Big Data",
    "education.0.institution": "EQF Level 5 | IES Zaidin Vergeles - Granada",
    "education.0.description": "Specialization in machine learning algorithms, deep learning, and scalable data architectures. Final project to be based on predictive models for backend optimization.",
    "education.1.year": "2024 - 2026",
    "education.1.title": "Higher Diploma in Web Applications Development",
    "education.1.institution": "EQF Level 5 | CESUR - Malaga",
    "education.1.description": "Core foundation in data structures, algorithms, and software engineering principles.",
    "education.2.year": "2015 - 2019",
    "education.2.title": "Vocational Certificate in Business Administration",
    "education.2.institution": "EQF Level 4 | FP Eden - Palencia",
    "education.2.description": "Hands-on experience understanding business logic and real life problem solving skills.",
    "education.3.year": "2009 - 2014",
    "education.3.title": "Compulsory Secondary Education",
    "education.3.institution": "EQF Level 3 | San Jose High School - Palencia",
    "education.3.description": "The start of the knowledge-seeking journey.",
    "career.title.main": "Career ",
    "career.title.accent": "trajectory",
    "career.subtitle": "This is just the beginning",
    "career.0.year": "03/2026 - 07/2026",
    "career.0.title": "Software Developer Internship",
    "career.0.institution": "Data Control SL | 4 months",
    "career.0.description": "Data manipulation using DataFlex and SQL. Building and maintaining databases, dashboards and moodle platforms.",
    "career.1.year": "01/2024 - 03/2026",
    "career.1.title": "Independence Compliance & Operations Specialist",
    "career.1.institution": "PricewaterhouseCoopers Service Delivery Center (Málaga) SL | 2 years 2 months",
    "career.1.description": "Company compliance and independence management for the multinational big four company PwC.",
    "career.2.year": "05/2022 - 12/2022",
    "career.2.title": "Banking Dispute Resolution Specialist",
    "career.2.institution": "OPPLUS SL - Malaga | 8 months",
    "career.2.description": "Customer service and resolution of disputes in the banking sector.",
    "career.3.year": "07/2021 - 12/2021",
    "career.3.title": "Photovoltaic Sales Operations Administrator",
    "career.3.institution": "Instalaciones Smart Spain SL - Palencia | 6 months",
    "career.3.description": "Coordination of contracts, public relationships, and sales processes.",
    "career.4.year": "01/2021 - 07/2021",
    "career.4.title": "Energy Sales Backoffice Administrator",
    "career.4.institution": "Oregon Comercial SL - Palencia | 7 months",
    "career.4.description": "Management and optimization of sales and customer relations processes.",
    "contact.title": "Let's talk",
    "contact.subtitle": "about what we can build",
    "contact.info.email": "Email",
    "contact.info.phone": "Phone",
    "contact.info.location": "Location",
    "contact.info.availability": "Availability",
    "contact.availability.text": "Available for remote and hybrid opportunities.",
    "contact.location.text": "Málaga - Spain",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.message": "Message",
    "contact.form.note": "I'll reply in the blink of an eye",
    "contact.form.send": "Send",
    "contact.toast.title": "Message sent",
    "contact.toast.message": "I'll get back to you soon.",
    "contact.alert.email": "Please enter a valid email address (e.g., name@domain.com).",
    "contact.alert.error": "Something went wrong. Please try again.",
    "contact.alert.network": "Network error. Please check your connection.",
    "contact.sending": "Sending...",
    "footer.credits.line1": 'Designed and built by <span class="text-gray-300">Jairo García Antolín</span>.',
    "footer.credits.line2": "Powered by Astro & Tailwind CSS.",
    "footer.navigate": "Navigate",
    "footer.connect": "Connect",
    "footer.copyright": "All rights reserved.",
  },

  es: {
    "page.title": "Jairo Garcia Antolin // Desarrollador de Software e IA",
    "nav.home": "Inicio",
    "nav.about": "Sobre mí",
    "nav.tech": "Tecnologías",
    "nav.projects": "Proyectos",
    "nav.education": "Formación",
    "nav.career": "Carrera",
    "nav.contact": "Contacto",
    "hero.typewriter": ["creo soluciones modernas", "diseño sistemas escalables", "priorizo la arquitectura limpia", "optimizo el rendimiento"],
    "hero.description": 'Mi objetivo es crear <span class="text-gray-200">soluciones de software modernas</span> que mejoren la experiencia de usuario e impulsen el éxito empresarial a través de la eficiencia y la escalabilidad.',
    "hero.cta": "Desarrollemos algo juntos",
    "hero.cv.english": "Inglés",
    "hero.cv.spanish": "Español",
    "about.whatido.title": 'Lo que <span class="text-gray-400">hago</span>',
    "about.whatido.p1": "Desarrollador de software en Málaga, especializado en la creación de sistemas robustos y escalables.",
    "about.whatido.p2": 'Actualmente estoy ampliando mis conocimientos en <span class="text-gray-200">Data Engineering, Inteligencia Artificial y soluciones Backend.</span><br /><br />Me apasiona crear sistemas que no solo funcionen a la perfección, sino que también procesen, validen y aprovechen los datos de forma inteligente.',
    "about.whoami.part1": "Quién",
    "about.whoami.part2": "soy",
    "about.whoami.p1": 'Soy un apasionado de <span class="text-gray-200">la tecnología, los videojuegos y descubrir cosas nuevas.</span>',
    "about.whoami.learning": 'Me engancha la sensación de <span class="text-gray-200">aprender</span> algo nuevo:',
    "about.whoami.typewriter": [" ciudades", " idiomas", " tecnologías", " videojuegos", " música", " películas", " culturas"],
    "about.whoami.p3": "Estoy convencido de que así es como seguimos creciendo y redescubriéndonos.",
    "about.whoami.elsword": 'Mi juego favorito de la infancia fue Elsword, un juego de acción 2.5D side-scrolling en el que <span class="text-gray-200">competí</span> contra jugadores de todo el mundo. <span class="text-gray-200">Gané el torneo europeo más importante de la historia de Elsword en 2016,</span> viajé a Colonia (Alemania) donde fui coronado campeón de Europa en la Gamescom tras una larga y reñida competición.',
    "about.whoami.discipline": 'Creo que la misma <span class="text-gray-200">disciplina</span> que necesité para ganar ese trofeo es la que se necesita para <span class="text-gray-200">optimizar, construir y encontrar soluciones</span> que realmente ayuden a las personas y mejoren los sistemas.',
    "tech.title.main": "Stack",
    "tech.title.accent": "tecnológico",
    "tech.subtitle": "Herramientas que marcan la diferencia",
    "tech.frontend.title": "Frontend",
    "tech.frontend.desc": "Diseño UX/UI",
    "tech.backend.title": "Backend",
    "tech.backend.desc": "Arquitectura y bases de datos",
    "tech.devops.title": "Dev Ops",
    "tech.devops.desc": "Despliegue y colaboración",
    "tech.ai.title": "Herramientas IA",
    "tech.ai.desc": "Productividad y asistencia al desarrollo",
    "projects.title.main": "Productos",
    "projects.title.accent": "creados",
    "projects.subtitle": "Aprender sin parar, crear sin límites",
    "projects.btn.live": "Demo",
    "projects.btn.features": "Detalles",
    "projects.btn.repo": "Repo",
    "projects.modal.label": "Detalles del proyecto",
    "projects.0.title": "Sampleton: Biblioteca de Audio",
    "projects.0.description": "Los usuarios pueden subir, explorar y reproducir muestras de audio en streaming, organizarlas en listas de reproducción, dejar comentarios y dar like a sus pistas favoritas. Esta aplicación full-stack incluye autenticación JWT, modo oscuro/claro, diseño responsive y un reproductor de audio persistente.",
    "projects.0.features.0": "Motor de reproducción global y persistente construido sobre el estado de React Layout/Outlet, garantizando reproducción ininterrumpida entre transiciones de rutas del cliente.",
    "projects.0.features.1": "Gestión CRUD RESTful completa para pistas de audio, carátulas personalizadas y listas de reproducción respaldadas por almacenamiento en Neon PostgreSQL.",
    "projects.0.features.2": "Arquitectura de seguridad basada en JWT con rutas protegidas, gestión automática de expiración de tokens mediante interceptores de Axios y cuenta demo para reclutadores con un solo clic.",
    "projects.0.features.3": "Control de permisos a nivel de objeto en los ViewSets de Django REST, restringiendo las acciones de eliminación y edición exclusivamente a los propietarios del recurso.",
    "projects.0.features.4": "Interfaz de detalle de pista con visualización de forma de onda simulada, contador de reproducciones, sistema de likes y feed de comentarios por pista.",
    "projects.0.features.5": "Validación de formularios en cliente y servidor mediante patrones regex para complejidad de contraseñas, verificación de email y restricciones de subida multipart/form-data.",
    "projects.0.features.6": "Dashboard personal con múltiples pestañas y motor de búsqueda en tiempo real para filtrado instantáneo de pistas, géneros, listas de reproducción e interacciones.",
    "projects.0.features.7": "Suite de tests automatizados con Pytest (pytest-django) para validar endpoints de autenticación, subida de archivos y operaciones de base de datos.",
    "projects.1.title": "Prototipo de Sistema RPG",
    "projects.1.description": "Desarrollado desde cero para dominar los fundamentos de programación. Incluye un motor de diálogos dinámico, una interfaz de inventario interactiva y un sistema robusto de persistencia y guardado/carga mediante serialización JSON, todo acompañado de pixel art original hecho a mano.",
    "projects.1.features.0": "Persistencia entre habitaciones y sistema de guardado/carga mediante parsing JSON. Para probar la persistencia entre salas, hay una habitación al final del camino derecho.",
    "projects.1.features.1": "Sistema de diálogos mediante sentencias switch y scripts personalizados para animaciones de texto.",
    "projects.1.features.2": "Sistema de inventario con interfaz de menú, usando arrays y scripts personalizados.",
    "projects.1.features.3": "Gráficos y animaciones 2D en pixel art hechos a mano.",
    "projects.1.controls.title": "Controles de teclado",
    "projects.1.controls.action.0": "Movimiento",
    "projects.1.controls.action.1": "Correr",
    "projects.1.controls.action.2": "Interactuar",
    "projects.1.controls.action.3": "Menú",
    "projects.1.controls.action.4": "Guardar partida",
    "projects.1.controls.action.5": "Cargar partida",
    "projects.1.controls.action.6": "Salir del juego",
    "projects.2.title": "Portfolio Web",
    "projects.2.description": "Un portfolio de desarrollador de alto rendimiento y diseño moderno, construido con Astro 5 y Tailwind CSS v4. Diseñado con foco en arquitectura limpia, animaciones fluidas, carga optimizada de recursos y UI/UX responsive.",
    "projects.2.features.0": "Desarrollado con Astro, Tailwind CSS y JavaScript para ofrecer un sitio estático optimizado en rendimiento y SEO.",
    "projects.2.features.1": "Animaciones de aparición fluidas y de alto rendimiento mediante Intersection Observer y transiciones CSS aceleradas por hardware.",
    "projects.2.features.2": "Generación de sitio estático (SSG) con Astro para una carga de recursos altamente optimizada y un rendimiento SEO superior.",
    "projects.2.features.3": "Interfaz responsive y mobile-first con navegación optimizada para táctil y componentes interactivos en Tailwind CSS puro.",
    "projects.3.title": "Analizador de Estadísticas Fantasy",
    "projects.3.description": "Un motor analítico diseñado para optimizar las plantillas de deportes fantasy. Recopila y agrega métricas de rendimiento y sistemas de puntuación para ofrecer valoraciones de mercado en tiempo real.",
    "projects.3.features.0": "Pipeline de web scraping automatizado que procesa más de 10.000 datos diarios.",
    "projects.3.features.1": "Integración de modelos de machine learning para puntuación predictiva.",
    "education.title.main": "Formación ",
    "education.title.accent": "académica",
    "education.subtitle": "Conocimiento en constante expansión",
    "education.0.year": "2026 - Actualidad",
    "education.0.title": "Curso de Especialización en IA y Big Data (Master FP)",
    "education.0.institution": "Nivel EQF 5 | IES Zaidín Vergeles - Granada",
    "education.0.description": "Especialización en algoritmos de machine learning, deep learning y arquitecturas de datos escalables. Proyecto final basado en modelos predictivos para optimización de backend.",
    "education.1.year": "2024 - 2026",
    "education.1.title": "Técnico Superior en Desarrollo de Aplicaciones Web",
    "education.1.institution": "Nivel EQF 5 | CESUR - Málaga",
    "education.1.description": "Formación sólida en estructuras de datos, algoritmos y principios de ingeniería de software.",
    "education.2.year": "2015 - 2019",
    "education.2.title": "Técnico en Gestión Administrativa",
    "education.2.institution": "Nivel EQF 4 | FP Edén - Palencia",
    "education.2.description": "Experiencia práctica en lógica empresarial y resolución de problemas reales.",
    "education.3.year": "2009 - 2014",
    "education.3.title": "Educación Secundaria Obligatoria",
    "education.3.institution": "Nivel EQF 3 | IES San José - Palencia",
    "education.3.description": "El inicio del camino hacia el conocimiento.",
    "career.title.main": "Trayectoria ",
    "career.title.accent": "profesional",
    "career.subtitle": "Esto es solo el principio",
    "career.0.year": "03/2026 - 07/2026",
    "career.0.title": "Desarrollador de Software (Becario)",
    "career.0.institution": "Data Control SL | 4 meses",
    "career.0.description": "Manipulación de datos con DataFlex y SQL. Construcción y mantenimiento de bases de datos, dashboards y plataformas Moodle.",
    "career.1.year": "01/2024 - 03/2026",
    "career.1.title": "Especialista en Cumplimiento e Independencia",
    "career.1.institution": "PricewaterhouseCoopers Service Delivery Center (Málaga) SL | 2 años y 2 meses",
    "career.1.description": "Gestión de cumplimiento normativo e independencia para la multinacional big four PwC.",
    "career.2.year": "05/2022 - 12/2022",
    "career.2.title": "Gestor de Disputas Bancarias",
    "career.2.institution": "OPPLUS SL - Málaga | 8 meses",
    "career.2.description": "Atención al cliente y resolución de incidencias en el sector bancario.",
    "career.3.year": "07/2021 - 12/2021",
    "career.3.title": "Administrativo de Instalaciones Fotovoltaicas",
    "career.3.institution": "Instalaciones Smart Spain SL - Palencia | 6 meses",
    "career.3.description": "Coordinación de contratos, relaciones públicas y procesos de venta.",
    "career.4.year": "01/2021 - 07/2021",
    "career.4.title": "Administrativo Backoffice en Comercialización de Energía",
    "career.4.institution": "Oregon Comercial SL - Palencia | 7 meses",
    "career.4.description": "Gestión y optimización de procesos de venta y relaciones con clientes.",
    "contact.title": "Hablemos",
    "contact.subtitle": "sobre lo que podemos desarrollar juntos",
    "contact.info.email": "Email",
    "contact.info.phone": "Teléfono",
    "contact.info.location": "Ubicación",
    "contact.info.availability": "Disponibilidad",
    "contact.availability.text": "Disponible para oportunidades en remoto e híbrido.",
    "contact.location.text": "Málaga - España",
    "contact.form.name": "Nombre",
    "contact.form.email": "Email",
    "contact.form.message": "Mensaje",
    "contact.form.note": "Respondo en un abrir y cerrar de ojos",
    "contact.form.send": "Enviar",
    "contact.toast.title": "Mensaje enviado",
    "contact.toast.message": "Te responderé lo antes posible.",
    "contact.alert.email": "Introduce un email válido (ej.: nombre@dominio.com).",
    "contact.alert.error": "Algo salió mal. Inténtalo de nuevo.",
    "contact.alert.network": "Error de conexión. Comprueba tu red.",
    "contact.sending": "Enviando...",
    "footer.credits.line1": 'Diseñado y desarrollado por <span class="text-gray-300">Jairo García Antolín</span>.',
    "footer.credits.line2": "Desarrollado con Astro y Tailwind CSS.",
    "footer.navigate": "Navegación",
    "footer.connect": "Conecta",
    "footer.copyright": "Todos los derechos reservados.",
  },
};

/** Returns the current language from localStorage, defaults to 'en' (or 'es' if browser is Spanish). */
export function getLang(): Lang {
  if (typeof window === "undefined") return "en";
  
  // Check if user has explicitly saved a language preference
  const savedLang = localStorage.getItem("lang") as Lang;
  if (savedLang) return savedLang;
  
  // If not saved, check browser language
  const browserLang = navigator.language || (navigator as any).userLanguage;
  if (browserLang && browserLang.toLowerCase().startsWith('es')) {
    return 'es';
  }
  
  return 'en';
}

/** Saves the selected language to localStorage. */
export function setLang(lang: Lang): void {
  localStorage.setItem("lang", lang);
}

/** Returns a translated string for the given key. */
export function t(key: string, lang?: Lang): string {
  const l = lang || getLang();
  const val = translations[l]?.[key] ?? translations.en[key] ?? key;
  if (Array.isArray(val)) return val[0];
  return val;
}
